baseURL = "https://dbraccia.com/"
locale = "en-US"
title = "Domenick J. Braccia"
theme = "Scholar-Lite"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = false
      xhtml = false
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
      wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.extensions]
      typographer = false
      linkify = false
      strikethrough = true
      definitionList = false
      footnote = true
      table = true
      taskList = false
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['$$', '$$'], ['\\[', '\\]']]
        inline = [['$', '$'], ['\\(', '\\)']]
  [markup.highlight]
    style = 'github'
    lineNos = false
    lineNumbersInTable = false
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    noClasses = false
    noHl = false
    tabWidth = 4

[taxonomies]
  tag = "tags"

[menus]
  [[menus.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menus.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menus.main]]
    name = "CV"
    url = "/cv/"
    weight = 3

[params]
  profilePhoto = "/images/profile.jpg"
  bio = """I am a Sr. Scientist in Computational Biology at [Cabaletta Bio](https://cabalettabio.com/). I apply bioinformatics, data science, and machine learning to the study of autoimmune disease."""

  [[params.social]]
    name = "Google Scholar"
    url = "https://scholar.google.com/citations?user=dIU2dxEAAAAJ&hl=en"

  [[params.social]]
    name = "GitHub"
    url = "https://github.com/dombraccia"

  [[params.social]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/dombraccia/"

  [[params.social]]
    name = "Twitter"
    url = "https://twitter.com/dombraccia"
